set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_disable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Sub]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sev_seg_leds[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_main]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports overflow]
set_property IOSTANDARD LVCMOS33 [get_ports negative]




set_property PACKAGE_PIN J14 [get_ports {led_disable[3]}]
set_property PACKAGE_PIN T9 [get_ports {led_disable[2]}]
set_property PACKAGE_PIN J18 [get_ports {led_disable[1]}]
set_property PACKAGE_PIN J17 [get_ports {led_disable[0]}]

set_property PACKAGE_PIN P14 [get_ports {led_enable[2]}]
set_property PACKAGE_PIN T14 [get_ports {led_enable[2]}]
set_property PACKAGE_PIN K2 [get_ports {led_enable[1]}]
set_property PACKAGE_PIN U13 [get_ports {led_enable[0]}]
set_property PACKAGE_PIN V10 [get_ports {A[3]}]
set_property PACKAGE_PIN U11 [get_ports {A[2]}]
set_property PACKAGE_PIN U12 [get_ports {A[1]}]
set_property PACKAGE_PIN H6 [get_ports {A[0]}]
set_property PACKAGE_PIN T13 [get_ports {B[3]}]
set_property PACKAGE_PIN R16 [get_ports {B[2]}]
set_property PACKAGE_PIN U8 [get_ports {B[1]}]
set_property PACKAGE_PIN T8 [get_ports {B[0]}]
set_property PACKAGE_PIN J15 [get_ports Sub]
set_property PACKAGE_PIN L18 [get_ports {sev_seg_leds[7]}]
set_property PACKAGE_PIN T11 [get_ports {sev_seg_leds[6]}]
set_property PACKAGE_PIN P15 [get_ports {sev_seg_leds[5]}]
set_property PACKAGE_PIN K13 [get_ports {sev_seg_leds[4]}]
set_property PACKAGE_PIN K16 [get_ports {sev_seg_leds[3]}]
set_property PACKAGE_PIN R10 [get_ports {sev_seg_leds[2]}]
set_property PACKAGE_PIN T10 [get_ports {sev_seg_leds[1]}]
set_property PACKAGE_PIN H15 [get_ports {sev_seg_leds[0]}]
set_property PACKAGE_PIN E3 [get_ports clk_main]
set_property PACKAGE_PIN P17 [get_ports reset]
set_property PACKAGE_PIN H17 [get_ports overflow]
set_property PACKAGE_PIN V11 [get_ports negative]


set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports sev_seg_leds]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports led_enable]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports negative]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports overflow]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports A]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports B]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports clk_main]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports Sub]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports reset]
set_switching_activity -toggle_rate 0.020 -static_probability 0.500 [get_ports led_disable]
